// Class: ReadMLP
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLP
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.10/09       [395785]
Creator        : cychuang
Date           : Wed Oct 16 13:07:13 2019
Host           : Linux cmsbuild49.cern.ch 2.6.32-696.10.2.el6.x86_64 #1 SMP Thu Sep 14 16:35:02 CEST 2017 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /wk_cms2/cychuang/CMSSW_9_4_2/src/wk_mva
Training events: 16233843
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "550" [Number of training cycles]
HiddenLayers: "N,N+5,3" [Specification of hidden layer architecture]
NeuronType: "sigmoid" [Neuron activation function type]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "True" [Print method-specific help message]
TestRate: "5" [Test for overtraining performed at each #th epochs]
UseRegulator: "False" [Use regulator to avoid over-training]
# Default:
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
EstimatorType: "CE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 8
top_mass                      top_mass                      top_mass                      top_mass                                                        'D'    [30.9399604797,6283.00878906]
w_mass                        w_mass                        w_mass                        w_mass                                                          'D'    [13.6341571808,4887.98876953]
j1j2_sumPt                    j1j2_sumPt                    j1j2_sumPt                    j1j2_sumPt                                                      'D'    [60.0183486938,2838.0078125]
j1j2_absdelEta                j1j2_absdelEta                j1j2_absdelEta                j1j2_absdelEta                                                  'D'    [0,4.79679441452]
j1j2_delPhi                   j1j2_delPhi                   j1j2_delPhi                   j1j2_delPhi                                                     'D'    [-3.14159178734,3.14159250259]
lepblep_sumPt                 lepblep_sumPt                 lepblep_sumPt                 lepblep_sumPt                                                   'D'    [60.075958252,2026.25830078]
lepblep_absdelEta             lepblep_absdelEta             lepblep_absdelEta             lepblep_absdelEta                                               'D'    [8.94069671631e-08,4.78118133545]
lepblep_delPhi                lepblep_delPhi                lepblep_delPhi                lepblep_delPhi                                                  'D'    [-3.14159107208,3.14159202576]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLP : public IClassifierReader {

 public:

   // constructor
   ReadMLP( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLP" ),
        fNvars( 8 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "top_mass", "w_mass", "j1j2_sumPt", "j1j2_absdelEta", "j1j2_delPhi", "lepblep_sumPt", "lepblep_absdelEta", "lepblep_delPhi" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 1;
      fVmin[4] = -1;
      fVmax[4] = 1;
      fVmin[5] = -1;
      fVmax[5] = 0.99999988079071;
      fVmin[6] = -1;
      fVmax[6] = 1;
      fVmin[7] = -1;
      fVmax[7] = 1;

      // initialize input variable types
      fType[0] = 'D';
      fType[1] = 'D';
      fType[2] = 'D';
      fType[3] = 'D';
      fType[4] = 'D';
      fType[5] = 'D';
      fType[6] = 'D';
      fType[7] = 'D';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLP() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][8];
   double fMax_1[3][8];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[8];
   double fVmax[8];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[8];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[5];
   double fWeightMatrix0to1[9][9];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[14][9];   // weight matrix from layer 1 to 2
   double fWeightMatrix2to3[4][14];   // weight matrix from layer 2 to 3
   double fWeightMatrix3to4[1][4];   // weight matrix from layer 3 to 4

   double * fWeights[5];
};

inline void ReadMLP::Initialize()
{
   // build network structure
   fLayers = 5;
   fLayerSize[0] = 9; fWeights[0] = new double[9]; 
   fLayerSize[1] = 9; fWeights[1] = new double[9]; 
   fLayerSize[2] = 14; fWeights[2] = new double[14]; 
   fLayerSize[3] = 4; fWeights[3] = new double[4]; 
   fLayerSize[4] = 1; fWeights[4] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = 5.77305218956949;
   fWeightMatrix0to1[1][0] = 119.264164156561;
   fWeightMatrix0to1[2][0] = 10.3589389300303;
   fWeightMatrix0to1[3][0] = -6.12238394444951;
   fWeightMatrix0to1[4][0] = -7.73882060487329;
   fWeightMatrix0to1[5][0] = -8.98745810617197;
   fWeightMatrix0to1[6][0] = -15.5639051734084;
   fWeightMatrix0to1[7][0] = 3.65400936057052;
   fWeightMatrix0to1[0][1] = 9.3212514086447;
   fWeightMatrix0to1[1][1] = -85.7311774829511;
   fWeightMatrix0to1[2][1] = -6.97867147680897;
   fWeightMatrix0to1[3][1] = 3.09406881631958;
   fWeightMatrix0to1[4][1] = 0.517977670262769;
   fWeightMatrix0to1[5][1] = -3.15065297057456;
   fWeightMatrix0to1[6][1] = 15.5863071524234;
   fWeightMatrix0to1[7][1] = 93.9233282393489;
   fWeightMatrix0to1[0][2] = -7.57026887800236;
   fWeightMatrix0to1[1][2] = -1.67262390666584;
   fWeightMatrix0to1[2][2] = -2.03737760050777;
   fWeightMatrix0to1[3][2] = 1.90713560231266;
   fWeightMatrix0to1[4][2] = 1.98105978480905;
   fWeightMatrix0to1[5][2] = -0.304760793795098;
   fWeightMatrix0to1[6][2] = -1.6936066026057;
   fWeightMatrix0to1[7][2] = 1.63515279823327;
   fWeightMatrix0to1[0][3] = -13.7355007921759;
   fWeightMatrix0to1[1][3] = 0.016445364564543;
   fWeightMatrix0to1[2][3] = 0.0134704710134591;
   fWeightMatrix0to1[3][3] = -0.118514349657267;
   fWeightMatrix0to1[4][3] = -0.752143515846291;
   fWeightMatrix0to1[5][3] = -1.12886805221452;
   fWeightMatrix0to1[6][3] = -0.315829404979266;
   fWeightMatrix0to1[7][3] = 0.24370198967171;
   fWeightMatrix0to1[0][4] = -5.29412429171308;
   fWeightMatrix0to1[1][4] = 0.033673524146112;
   fWeightMatrix0to1[2][4] = 0.0293557577429057;
   fWeightMatrix0to1[3][4] = -0.0135812453611024;
   fWeightMatrix0to1[4][4] = -4.35091132343536;
   fWeightMatrix0to1[5][4] = 3.83536530702563;
   fWeightMatrix0to1[6][4] = -0.0395861836456423;
   fWeightMatrix0to1[7][4] = 0.0631668439861971;
   fWeightMatrix0to1[0][5] = 0.803842491296133;
   fWeightMatrix0to1[1][5] = -0.498766151915167;
   fWeightMatrix0to1[2][5] = 2.75826253040607;
   fWeightMatrix0to1[3][5] = -3.59816383093723;
   fWeightMatrix0to1[4][5] = 0.830812639220461;
   fWeightMatrix0to1[5][5] = 0.461165419046693;
   fWeightMatrix0to1[6][5] = -35.7551771889061;
   fWeightMatrix0to1[7][5] = 0.620088340442112;
   fWeightMatrix0to1[0][6] = 0.567765242100836;
   fWeightMatrix0to1[1][6] = -0.0481555891701798;
   fWeightMatrix0to1[2][6] = 1.84478528242569;
   fWeightMatrix0to1[3][6] = -1.86194405356479;
   fWeightMatrix0to1[4][6] = 0.0432422118031107;
   fWeightMatrix0to1[5][6] = -0.0331830463927854;
   fWeightMatrix0to1[6][6] = -2.912085001397;
   fWeightMatrix0to1[7][6] = 0.00976225865822908;
   fWeightMatrix0to1[0][7] = -0.0483700733519937;
   fWeightMatrix0to1[1][7] = 0.0158158130808592;
   fWeightMatrix0to1[2][7] = 4.37665170057571;
   fWeightMatrix0to1[3][7] = 4.39358776549724;
   fWeightMatrix0to1[4][7] = -0.00109254367275897;
   fWeightMatrix0to1[5][7] = -0.0178217871446843;
   fWeightMatrix0to1[6][7] = -0.00170528426627158;
   fWeightMatrix0to1[7][7] = -0.0011937015703329;
   fWeightMatrix0to1[0][8] = -2.31196686526221;
   fWeightMatrix0to1[1][8] = 28.380798302155;
   fWeightMatrix0to1[2][8] = 3.61461270371773;
   fWeightMatrix0to1[3][8] = -4.5253971988593;
   fWeightMatrix0to1[4][8] = -3.82738486625791;
   fWeightMatrix0to1[5][8] = -11.572733215922;
   fWeightMatrix0to1[6][8] = -37.1735034927415;
   fWeightMatrix0to1[7][8] = 96.6594307619812;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = 0.126562027030847;
   fWeightMatrix1to2[1][0] = 11.2773070957404;
   fWeightMatrix1to2[2][0] = 0.251277935539551;
   fWeightMatrix1to2[3][0] = 0.632267892445036;
   fWeightMatrix1to2[4][0] = 0.156451127732207;
   fWeightMatrix1to2[5][0] = -0.631913606088821;
   fWeightMatrix1to2[6][0] = -0.0820649469325518;
   fWeightMatrix1to2[7][0] = -1.09768222136694;
   fWeightMatrix1to2[8][0] = -0.186930367448325;
   fWeightMatrix1to2[9][0] = -0.787350826138108;
   fWeightMatrix1to2[10][0] = -0.0450901748011354;
   fWeightMatrix1to2[11][0] = 0.0545156487278401;
   fWeightMatrix1to2[12][0] = 0.177075389101304;
   fWeightMatrix1to2[0][1] = -1.80266509775463;
   fWeightMatrix1to2[1][1] = -0.360515558540162;
   fWeightMatrix1to2[2][1] = -8.18518444096543;
   fWeightMatrix1to2[3][1] = -4.3029046267831;
   fWeightMatrix1to2[4][1] = -1.29137556571926;
   fWeightMatrix1to2[5][1] = -0.435125909893702;
   fWeightMatrix1to2[6][1] = -6.28278178077629;
   fWeightMatrix1to2[7][1] = 1.43087274887993;
   fWeightMatrix1to2[8][1] = -4.78016421613997;
   fWeightMatrix1to2[9][1] = 0.265601813840136;
   fWeightMatrix1to2[10][1] = 13.8804575176629;
   fWeightMatrix1to2[11][1] = -6.42230380511132;
   fWeightMatrix1to2[12][1] = 4.41079854712769;
   fWeightMatrix1to2[0][2] = -0.18294197738148;
   fWeightMatrix1to2[1][2] = 0.212423965502715;
   fWeightMatrix1to2[2][2] = -0.374609956570918;
   fWeightMatrix1to2[3][2] = 0.394775791206068;
   fWeightMatrix1to2[4][2] = 2.29953979196123;
   fWeightMatrix1to2[5][2] = 5.58193542176727;
   fWeightMatrix1to2[6][2] = 0.236714629861942;
   fWeightMatrix1to2[7][2] = -18.9770657697618;
   fWeightMatrix1to2[8][2] = 0.159997118036443;
   fWeightMatrix1to2[9][2] = -11.5691747962817;
   fWeightMatrix1to2[10][2] = 0.174736244936932;
   fWeightMatrix1to2[11][2] = 0.101242551709352;
   fWeightMatrix1to2[12][2] = 0.149947079404117;
   fWeightMatrix1to2[0][3] = 0.2873077028631;
   fWeightMatrix1to2[1][3] = -0.000244502993575718;
   fWeightMatrix1to2[2][3] = 0.109424156467065;
   fWeightMatrix1to2[3][3] = -0.982479271532873;
   fWeightMatrix1to2[4][3] = 11.4914933962098;
   fWeightMatrix1to2[5][3] = 9.54620994343609;
   fWeightMatrix1to2[6][3] = -0.147132878640486;
   fWeightMatrix1to2[7][3] = 18.6911150038686;
   fWeightMatrix1to2[8][3] = -0.131213255467639;
   fWeightMatrix1to2[9][3] = -12.8393275407481;
   fWeightMatrix1to2[10][3] = -0.117268645200694;
   fWeightMatrix1to2[11][3] = 0.0588216521931493;
   fWeightMatrix1to2[12][3] = -0.101728976440667;
   fWeightMatrix1to2[0][4] = 2.16633752068373;
   fWeightMatrix1to2[1][4] = -4.31647126293044;
   fWeightMatrix1to2[2][4] = 3.57487677791321;
   fWeightMatrix1to2[3][4] = 0.411706676617397;
   fWeightMatrix1to2[4][4] = -1.32583940376495;
   fWeightMatrix1to2[5][4] = -2.78895104809878;
   fWeightMatrix1to2[6][4] = 4.11883904651086;
   fWeightMatrix1to2[7][4] = -1.11189376448952;
   fWeightMatrix1to2[8][4] = 2.34767678748315;
   fWeightMatrix1to2[9][4] = -3.61712574369447;
   fWeightMatrix1to2[10][4] = 0.625127458315347;
   fWeightMatrix1to2[11][4] = -5.89070686365409;
   fWeightMatrix1to2[12][4] = -1.00033258870601;
   fWeightMatrix1to2[0][5] = 2.2441488505218;
   fWeightMatrix1to2[1][5] = 16.1525084286605;
   fWeightMatrix1to2[2][5] = 3.70512169550326;
   fWeightMatrix1to2[3][5] = 0.290322080882231;
   fWeightMatrix1to2[4][5] = -2.56267101847;
   fWeightMatrix1to2[5][5] = -3.48237346009662;
   fWeightMatrix1to2[6][5] = 4.31175670608799;
   fWeightMatrix1to2[7][5] = -1.93527826473798;
   fWeightMatrix1to2[8][5] = 2.61399287176484;
   fWeightMatrix1to2[9][5] = -4.64816342175179;
   fWeightMatrix1to2[10][5] = 0.827884741027697;
   fWeightMatrix1to2[11][5] = -5.87727947523255;
   fWeightMatrix1to2[12][5] = -0.673402286230113;
   fWeightMatrix1to2[0][6] = 1.00526236133891;
   fWeightMatrix1to2[1][6] = -0.121039218178785;
   fWeightMatrix1to2[2][6] = -0.547007792167842;
   fWeightMatrix1to2[3][6] = -0.361744847636125;
   fWeightMatrix1to2[4][6] = -1.0134763390691;
   fWeightMatrix1to2[5][6] = -11.1028018486715;
   fWeightMatrix1to2[6][6] = 0.36434491815872;
   fWeightMatrix1to2[7][6] = 8.27413318924405;
   fWeightMatrix1to2[8][6] = -0.128152968136191;
   fWeightMatrix1to2[9][6] = -11.2694887068649;
   fWeightMatrix1to2[10][6] = -0.384263176896591;
   fWeightMatrix1to2[11][6] = -0.172886181793825;
   fWeightMatrix1to2[12][6] = 0.133375536976467;
   fWeightMatrix1to2[0][7] = 9.23749675711516;
   fWeightMatrix1to2[1][7] = 3.2447166306416;
   fWeightMatrix1to2[2][7] = -3.36519878387452;
   fWeightMatrix1to2[3][7] = -2.07779673144694;
   fWeightMatrix1to2[4][7] = -0.605275272814459;
   fWeightMatrix1to2[5][7] = -1.34295390362639;
   fWeightMatrix1to2[6][7] = -7.21728518412632;
   fWeightMatrix1to2[7][7] = -0.879230021702122;
   fWeightMatrix1to2[8][7] = -5.43466544033555;
   fWeightMatrix1to2[9][7] = -1.9779011000016;
   fWeightMatrix1to2[10][7] = -11.3744623018261;
   fWeightMatrix1to2[11][7] = 2.57410188317075;
   fWeightMatrix1to2[12][7] = -10.7001999798002;
   fWeightMatrix1to2[0][8] = -6.90819729210801;
   fWeightMatrix1to2[1][8] = -14.3697170046358;
   fWeightMatrix1to2[2][8] = 5.02702046903048;
   fWeightMatrix1to2[3][8] = 2.01577876008428;
   fWeightMatrix1to2[4][8] = -8.74234177153646;
   fWeightMatrix1to2[5][8] = -10.3820445116042;
   fWeightMatrix1to2[6][8] = -3.72001089441842;
   fWeightMatrix1to2[7][8] = -0.486627523734618;
   fWeightMatrix1to2[8][8] = 0.896666327924104;
   fWeightMatrix1to2[9][8] = 6.90419789630259;
   fWeightMatrix1to2[10][8] = -4.7651544152899;
   fWeightMatrix1to2[11][8] = 7.21618921625053;
   fWeightMatrix1to2[12][8] = 0.197595352025929;
   // weight matrix from layer 2 to 3
   fWeightMatrix2to3[0][0] = -1.2470035383179;
   fWeightMatrix2to3[1][0] = -3.00549819967828;
   fWeightMatrix2to3[2][0] = 3.01352818537777;
   fWeightMatrix2to3[0][1] = 0.763254847837553;
   fWeightMatrix2to3[1][1] = -0.613592853921016;
   fWeightMatrix2to3[2][1] = -0.560567957134181;
   fWeightMatrix2to3[0][2] = 3.3332306656711;
   fWeightMatrix2to3[1][2] = -3.64273997462076;
   fWeightMatrix2to3[2][2] = -8.68959896963931;
   fWeightMatrix2to3[0][3] = 2.45611517550128;
   fWeightMatrix2to3[1][3] = 3.00890322012036;
   fWeightMatrix2to3[2][3] = -0.535869992590094;
   fWeightMatrix2to3[0][4] = 0.578703263158283;
   fWeightMatrix2to3[1][4] = 0.174851010818722;
   fWeightMatrix2to3[2][4] = -0.442627467027288;
   fWeightMatrix2to3[0][5] = -4.35460596271718;
   fWeightMatrix2to3[1][5] = -3.57055208290058;
   fWeightMatrix2to3[2][5] = 6.61404557679596;
   fWeightMatrix2to3[0][6] = -4.69132881948116;
   fWeightMatrix2to3[1][6] = 2.99585869894089;
   fWeightMatrix2to3[2][6] = 8.79511714848786;
   fWeightMatrix2to3[0][7] = 1.8030202743005;
   fWeightMatrix2to3[1][7] = 1.58079057279723;
   fWeightMatrix2to3[2][7] = -1.86103694584186;
   fWeightMatrix2to3[0][8] = -1.63138580732381;
   fWeightMatrix2to3[1][8] = 12.0533320284118;
   fWeightMatrix2to3[2][8] = 4.97012295912953;
   fWeightMatrix2to3[0][9] = -2.59984032656552;
   fWeightMatrix2to3[1][9] = -3.0157969473228;
   fWeightMatrix2to3[2][9] = 4.41702677129496;
   fWeightMatrix2to3[0][10] = -0.450564629612619;
   fWeightMatrix2to3[1][10] = -4.56995990903105;
   fWeightMatrix2to3[2][10] = 3.56011554304941;
   fWeightMatrix2to3[0][11] = -3.34992383141704;
   fWeightMatrix2to3[1][11] = -0.200589880082371;
   fWeightMatrix2to3[2][11] = 10.0867844548725;
   fWeightMatrix2to3[0][12] = -2.73002553733453;
   fWeightMatrix2to3[1][12] = -0.637013548309159;
   fWeightMatrix2to3[2][12] = 6.32630597911064;
   fWeightMatrix2to3[0][13] = -3.85654525144506;
   fWeightMatrix2to3[1][13] = 3.90641864147684;
   fWeightMatrix2to3[2][13] = -1.60320808956197;
   // weight matrix from layer 3 to 4
   fWeightMatrix3to4[0][0] = 6.24281236291405;
   fWeightMatrix3to4[0][1] = 1.94187582983494;
   fWeightMatrix3to4[0][2] = -2.85751046207394;
   fWeightMatrix3to4[0][3] = -3.46634979070773;
}

inline double ReadMLP::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]-1; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = ActivationFnc(fWeights[2][o]);
   }
   // layer 2 to 3
   for (int o=0; o<fLayerSize[3]-1; o++) {
      for (int i=0; i<fLayerSize[2]; i++) {
         double inputVal = fWeightMatrix2to3[o][i] * fWeights[2][i];
         fWeights[3][o] += inputVal;
      }
      fWeights[3][o] = ActivationFnc(fWeights[3][o]);
   }
   // layer 3 to 4
   for (int o=0; o<fLayerSize[4]; o++) {
      for (int i=0; i<fLayerSize[3]; i++) {
         double inputVal = fWeightMatrix3to4[o][i] * fWeights[3][i];
         fWeights[4][o] += inputVal;
      }
      fWeights[4][o] = OutputActivationFnc(fWeights[4][o]);
   }

   return fWeights[4][0];
}

double ReadMLP::ActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}
double ReadMLP::OutputActivationFnc(double x) const {
   // sigmoid
   return 1.0/(1.0+exp(-x));
}
   
// Clean up
inline void ReadMLP::Clear() 
{
   // clean up the arrays
   for (int lIdx = 0; lIdx < 5; lIdx++) {
      delete[] fWeights[lIdx];
   }
}
   inline double ReadMLP::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadMLP::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 64.2460479736;
   fMax_1[0][0] = 1856.01599121;
   fMin_1[1][0] = 30.9399604797;
   fMax_1[1][0] = 6283.00878906;
   fMin_1[2][0] = 30.9399604797;
   fMax_1[2][0] = 6283.00878906;
   fMin_1[0][1] = 17.8555870056;
   fMax_1[0][1] = 1452.07287598;
   fMin_1[1][1] = 13.6341571808;
   fMax_1[1][1] = 4887.98876953;
   fMin_1[2][1] = 13.6341571808;
   fMax_1[2][1] = 4887.98876953;
   fMin_1[0][2] = 60.0529937744;
   fMax_1[0][2] = 1147.6652832;
   fMin_1[1][2] = 60.0183486938;
   fMax_1[1][2] = 2838.0078125;
   fMin_1[2][2] = 60.0183486938;
   fMax_1[2][2] = 2838.0078125;
   fMin_1[0][3] = 3.57627868652e-07;
   fMax_1[0][3] = 4.47416448593;
   fMin_1[1][3] = 0;
   fMax_1[1][3] = 4.79679441452;
   fMin_1[2][3] = 0;
   fMax_1[2][3] = 4.79679441452;
   fMin_1[0][4] = -3.14158034325;
   fMax_1[0][4] = 3.14159083366;
   fMin_1[1][4] = -3.14159178734;
   fMax_1[1][4] = 3.14159250259;
   fMin_1[2][4] = -3.14159178734;
   fMax_1[2][4] = 3.14159250259;
   fMin_1[0][5] = 60.1165008545;
   fMax_1[0][5] = 1369.08850098;
   fMin_1[1][5] = 60.075958252;
   fMax_1[1][5] = 2026.25830078;
   fMin_1[2][5] = 60.075958252;
   fMax_1[2][5] = 2026.25830078;
   fMin_1[0][6] = 2.08616256714e-06;
   fMax_1[0][6] = 4.66284751892;
   fMin_1[1][6] = 8.94069671631e-08;
   fMax_1[1][6] = 4.78118133545;
   fMin_1[2][6] = 8.94069671631e-08;
   fMax_1[2][6] = 4.78118133545;
   fMin_1[0][7] = -3.14158987999;
   fMax_1[0][7] = 3.14158725739;
   fMin_1[1][7] = -3.14159107208;
   fMax_1[1][7] = 3.14159202576;
   fMin_1[2][7] = -3.14159107208;
   fMax_1[2][7] = 3.14159202576;
}

//_______________________________________________________________________
inline void ReadMLP::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 8;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   static std::vector<int> indicesGet;
   static std::vector<int> indicesPut;

   if ( indicesGet.empty() ) { 
      indicesGet.reserve(fNvars);
      indicesGet.push_back( 0);
      indicesGet.push_back( 1);
      indicesGet.push_back( 2);
      indicesGet.push_back( 3);
      indicesGet.push_back( 4);
      indicesGet.push_back( 5);
      indicesGet.push_back( 6);
      indicesGet.push_back( 7);
   } 
   if ( indicesPut.empty() ) { 
      indicesPut.reserve(fNvars);
      indicesPut.push_back( 0);
      indicesPut.push_back( 1);
      indicesPut.push_back( 2);
      indicesPut.push_back( 3);
      indicesPut.push_back( 4);
      indicesPut.push_back( 5);
      indicesPut.push_back( 6);
      indicesPut.push_back( 7);
   } 

   static std::vector<double> dv;
   dv.resize(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<8;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadMLP::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLP::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
